"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/toaster"
import { useSearchParams } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children, params
}: {
  children: React.ReactNode,
  params: { userId: string } 
}) {

  return (
        <div className = "flex h-full min-h-screen bg-[#1D232A]">
            <div className="w-1/5 h-full"><Sidebar userId={params.userId as string}/></div>
            <div className="w-full h-full">{children}</div> 
        </div> 
  );
}
