import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div className = "flex h-screen bg-[#1D232A]">
            <div className="w-1/5 h-full"><Sidebar /></div>
            <div className="w-full h-full">{children}</div> 
        </div> 
  );
}
